name: 'Deltadox-Android'
description: 'SDK for anything your problem to make easier developing android apps'
author: 'deltadox'
branding:
  icon: archive
  color: blue
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
